---
- name: add gpg key
  apt_key:
    url: "{{ rspamd_key }}"
    state: present

- name: add repository
  apt_repository:
    repo: deb http://rspamd.com/apt-stable/ bionic main
    state: present
    filename: rspamd

- name: install packages
  with_items: "{{ rspamd_packages }}"
  package:
    name: "{{ item.name }}"
  notify:
    - restart rspamd

- name: configure worker
  template:
    src: worker-controller.inc.j2
    dest: /etc/rspamd/worker-controller.inc
  notify:
    - restart rspamd

- name: configure dkim signing
  template:
    src: dkim_signing.conf.j2
    dest: /etc/rspamd/local.d/dkim_signing.conf
  notify:
    - restart rspamd

- name: configure milter
  template:
    src: milter_headers.conf.j2
    dest: /etc/rspamd/local.d/milter_headers.conf
  notify:
    - restart rspamd

- name: create dkim directory
  file:
    path: /var/db/rspamd/dkim
    state: directory

- name: generate dkim key
  command: rspamadm dkim_keygen -s mail -k "/var/db/rspamd/dkim/{{ domain }}.mail.key" -d "{{ domain }}" >"/var/db/rspamd/dkim/{{ domain }}.mail.public"
  args:
    creates: "/var/db/rspamd/dkim/{{ domain }}.mail.key"
  notify:
    - restart rspamd
